name: Corprus Crucible Manufacturing

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main
    tags: ['*']

jobs:
  build-lib:
    permissions:
      contents: write
      pages: write
      id-token: write
    uses: DreamWeave-MP/StroggForge/.github/workflows/libGlobalBuild.yml@v14
    secrets: inherit
    with:
      crate_names: '["dream_archive"]'
      # dependent_repo_names: '[]'
      generate_benchmarks: true
